name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Tell us what you expected
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Tell us what actually happened
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (system unusable)
        - High (major feature broken)
        - Medium (minor feature issue)
        - Low (cosmetic issue)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g., macOS 13.0, Ubuntu 22.04, Windows 11]
        - Node.js version: [e.g., 18.17.0]
        - v-secure version: [e.g., 1.0.0]
        - Database: [e.g., PostgreSQL 14, Supabase]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Errors
      description: Please paste any relevant error messages or logs (sanitize sensitive information!)
      render: shell
      placeholder: Paste logs here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, etc.)
      placeholder: Any additional information

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched for similar issues
          required: true
        - label: I have sanitized all sensitive information from logs
          required: true
        - label: I am using a supported version
          required: false
