name: Security Vulnerability
description: Report a security vulnerability (use private reporting!)
title: "SECURITY: "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        # STOP - DO NOT FILE PUBLIC SECURITY ISSUES

        If you have discovered a security vulnerability, please **DO NOT** create a public issue.

        Instead, please report it privately via email to:

        **security@lanonasis.com**

        We take security seriously and will respond promptly.

        ### Why Not Public Issues?

        - Public disclosure can put users at risk
        - Attackers can exploit vulnerabilities before fixes are available
        - We need time to develop and test fixes
        - Users need time to update

        ### What Happens Next?

        1. Send email to security@lanonasis.com with vulnerability details
        2. You'll receive acknowledgment within 24 hours
        3. We'll validate and assess severity within 72 hours
        4. We'll work on a fix and keep you updated
        5. We'll release a security advisory and fix
        6. We'll credit you in our security hall of fame (if desired)

        Thank you for helping keep v-secure secure!

  - type: checkboxes
    id: confirm
    attributes:
      label: I Understand
      options:
        - label: I understand I should NOT file public security issues
          required: true
        - label: I will email security@lanonasis.com instead
          required: true
